### ISSUE TITLE
Reference Guide?

### ISSUE THREAD

**Issue by jakoblorz** [chrizzzlybear/jarves#1]
This project looks very promising - does it have something in common with the [example on scikit's website](http://scikit-learn.org/stable/auto_examples/applications/plot_stock_market.html#sphx-glr-auto-examples-applications-plot-stock-market-py), @chrizzzlybear? Seems to be somewhat similar!

**Comment by chrizzzlybear** [comment]
Yeah, indeed @jakoblorz - it has something in common with this example (or at least should one day end where they are already) I just got distracted and try to resume work (some was done locally).
